version: '3'

services:

  harena-space:
    environment:
      - ENV_SILENT=true            
      - HOST=0.0.0.0
      - PORT=10010
      - NODE_ENV=production
      - APP_NAME=harena-space
      - APP_URL=http://0.0.0.0:10010
      - CACHE_VIEWS=false
      - APP_KEY=Xw8Ctu827gw290qDx4GSnUlyTY3a6x
      - HASH_DRIVER=bcrypt
      - HARENA_SPACE_URL=http://harena.ds4h.org/space
      - HARENA_SPACE_API_VERSION=v1
      - HARENA_MANAGER_URL=http://harena.ds4h.org/manager
      - HARENA_MANAGER_API_VERSION=v1
      - HARENA_LOGGER_URL=http://harena.ds4h.org/logger
      - HARENA_LOGGER_API_VERSION=v1      



